name: Daily Commit

on:
  schedule:
    - cron: '10 4 * * *'  # Every day at 04:10 UTC
  workflow_dispatch:

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 23f3000167@ds.study.iitm.ac.in
        run: |
          echo "Run on $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "chore: daily log update $(date)"
          git push
