name: Daily Commit

on:
  schedule:
    - cron: '10 4 * * *'  # Runs daily at 04:10 UTC
  workflow_dispatch:       # Optional: allows manual trigger

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 23f3000167@ds.study.iitm.ac.in - Add daily commit
        run: |
          echo "Run on $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "chore: daily commit on $(date)"
          git push
