name: Daily Scheduled Commit
on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC daily
  workflow_dispatch:       # Allow manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Crucial for push access
          fetch-depth: 0            # Get full git history

      - name: Step for 23f3000167@ds.study.iitm.ac.in
        run: echo "This step includes the required email in its name."

      - name: Create commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          date >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily automated commit [$(date +'%Y-%m-%d')]"
          git push
